jacob-macleod/Dolphin-Flashcard-App

workflow/workflow.yml, workflows/workflow.yml
=> 1 initial code

docs/card_management.md
Hi Jacob, please review this documentation for card_management's endpoints and point out the errors or omissions in it, if any. Thank you.
=> documented the endpoints in card_management.py

.github/workflows/workflow.yml
=> Changed server setup

CHANGELOG.md, backend/__init__.py, backend/database/database_config.py, backend/routes/api/statistics.py, bump_version.sh, data.json, frontend/package-lock.json, frontend/package.json, frontend/src/api/Api.js, frontend/src/api/config.js, frontend/src/componments/HamburgerBar.css, frontend/src/componments/HamburgerBar.js, frontend/src/componments/Image.js, frontend/src/containers/EditGoalPopup.js, frontend/src/containers/MobileSidePanel.css, frontend/src/containers/MobileSidePanel.js, frontend/src/containers/NewGoalPopup.css, frontend/src/containers/NewGoalPopup.js, frontend/src/containers/StreakWidget.js, frontend/src/screens/Dashboard.js, frontend/src/screens/SignIn.js, frontend/src/static/blue-hamburger-menu.svg, frontend/src/static/grey-hamburger-menu.svg, frontend/src/textSizes.js
=> MINOR: Dashboard page mobile

.github/workflows/code_linting.yml, CHANGELOG.md, backend/__init__.py, frontend/package-lock.json, frontend/package.json, frontend/src/api/temp_secretKeys.js, package-lock.json, package.json
- N/A
- Solved an issue where jsonp was not downloaded
- N/A
- N/A
=> PATCH: Fixed build error

CHANGELOG.md, backend/__init__.py, backend/database/database_config.py, backend/database/handlers/folders.py, backend/database/handlers/statistics.py, backend/routes/api/card_management.py, backend/routes/api/statistics.py, frontend/src/App.js, frontend/src/api/Api.js, frontend/src/api/config.js, frontend/src/componments/AccountDropdown/AccountDropdown.js, frontend/src/containers/ErrorBoundary/ErrorBoundary.js, frontend/src/containers/FlashcardOverview/FlashcardFolder/FlashcardFolder.js, frontend/src/containers/FlashcardOverview/FlashcardOverview.js, frontend/src/containers/Modal/CardOperationsPopup/CardOperationsPopup.js, frontend/src/containers/Modal/DeleteFolderConfirmation/DeleteFolderConfirmation.js, frontend/src/containers/Modal/DeleteFolderConfirmation/index.js, frontend/src/containers/Modal/FolderOperationsPopup/FolderOperationsPopup.css, frontend/src/containers/Modal/FolderOperationsPopup/FolderOperationsPopup.js, frontend/src/containers/Modal/FolderOperationsPopup/index.js, frontend/src/containers/Modal/RenameFolderPopup/RenameFolderPopup.js, frontend/src/containers/Modal/RenameFolderPopup/index.js, frontend/src/containers/Modal/RenamePopup/index.js, frontend/src/containers/SidePanel/SidePanel.js, frontend/src/screens/Flashcards.js, frontend/src/screens/PageNotFound.js
- New backend methods and frontend components to allow folders to be renamed and deleted
- Added new 404 error page
- Added new ErrorBoundary component to show when there is a Frontend React error
- Added checking to see if the user is signed in for all pages
- Added ability to sign out
- Issue where the XP, streak and heatmap were not updated when a user revised cards
=> MINOR: Streak calculation not working

CHANGELOG.md, backend/__init__.py, backend/database/database_config.py, backend/database/jwt_handler.py, backend/routes/api/authentication.py, frontend/src/api/Authentication.js, frontend/src/api/config.js, frontend/src/screens/SignIn.js, testing/test_api.py
- Solve bug in server and added sign-in method
=> MINOR: Sign in method

CHANGELOG.md, backend/__init__.py, frontend/src/App.js, testing/test_api.py
=> PATCH: Released Alpha

CHANGELOG.md, backend/__init__.py, frontend/src/classes/FlashcardReviewer.js, frontend/src/containers/DailyFlashcardBrowser/DailyFlashcardBrowser.js
- Fixed issue in the card review algorithm
=> PATCH: Fixed bug in card review algorithm

.github/workflows/bump_version.yml, .github/workflows/code_linting.yml, CHANGELOG.md, backend/__init__.py, bump_version.sh, frontend/src/App.js, frontend/src/componments/Button/Button.css, frontend/src/componments/LandingPageFooter/LandingPageFooter.js, frontend/src/componments/SignInButton/SignInButton.js, frontend/src/componments/SignInButton/index.js, frontend/src/componments/Text/Subheader/Subheader.css, frontend/src/containers/BlobBackground/BlobBackground.js, frontend/src/containers/MailChimpWidget/MailChimpInput/MailChimpInput.js, frontend/src/screens/LandingPage.js, frontend/src/screens/SignIn.css, frontend/src/screens/SignIn.js
v6.1.1 - 2025-01-31
- Fixed sign in errors on new landing page
- Fixed responsive design in the landing page (by adding the useEffect that listens to screen width changes)
- Fixed dimensions and object fit issues with the landing page coffee/table image
- Extracted sign in button + related functionality to separate SignInButton component
- The email address in the landing page footer section is now constructed programatically to stop web crawlers from spamming the email (good practice)
- When the email displayed in the landing page footer is clicked, your emails open
- Sign in button component now uses flex-box and the contents are justified as "flex-start"
=> PATCH: Bug fixes for landing page

CHANGELOG.md, backend/__init__.py, frontend/src/containers/UserProfileHeader/UserProfileHeader.js
**v6.1.3 - 2025-02-12**
Resolves #178 
- Made user's name right-aligned in the left menu
=> PATCH: Made name right aligned in left menu

CHANGELOG.md, backend/__init__.py, frontend/src/screens/LandingPage.js
Fixes #195 
- Completed the FAQ section of the landing page.
=> PATCH: Fix The F&Q Text on the Landing Page

CHANGELOG.md, backend/__init__.py, frontend/src/api/Api.js, frontend/src/api/Authentication.js, frontend/src/api/config.js, frontend/src/containers/CardOverview/CardOverview.js, frontend/src/containers/DailyFlashcardBrowser/DailyFlashcardBrowser.js, frontend/src/containers/MailChimpWidget/MailChimpWidget.js, frontend/src/containers/TotalFlashcardBrowser/PreviewTotalFlashcardBrowser.js, frontend/src/containers/TotalFlashcardBrowser/TotalFlashcardBrowser.js, frontend/src/hooks/getCommunityFlashcard.js, frontend/src/hooks/getFlashcardDataForMultipleCards.js, frontend/src/screens/EditFlashcard.js, frontend/src/screens/PreviewFlashcard.js, frontend/src/screens/ViewFlashcards.js, frontend/src/static/expand-icon.svg
=> PATCH: Added loading animations

CHANGELOG.md, backend/__init__.py, backend/database/handlers/goals.py
First we check for data then delete so it handles the error 
issue - #138
=> PATCH: delete goals Error Handling

.gitignore, CHANGELOG.md, backend/__init__.py, dolphin_cli.sh
- Developed CLI Tools for Managing Backend, Frontend, Database, Tests and Configurations.
FIXES: #166
=> MINOR: CLI Tools for Managing Backend, Frontend, Database, Tests and Configurations.

CHANGELOG.md, backend/__init__.py, frontend/package-lock.json, frontend/src/App.js, frontend/src/componments/GhostButton/GhostButton.css, frontend/src/componments/GhostButton/GhostButton.js, frontend/src/containers/DailyFlashcardBrowser/DailyFlashcardBrowser.css, frontend/src/containers/DailyFlashcardBrowser/DailyFlashcardBrowser.js, frontend/src/containers/TotalFlashcardBrowser/RenderTotalFlashcardBrowser.js, frontend/src/containers/TotalFlashcardBrowser/TotalFlashcardBrowser.css, frontend/src/static/exit-fullscreen-icon.svg
This PR introduces a fullscreen mode for the flashcard viewer. When the user clicks the expand button, the flashcard will take up the entire screen, and other components (like the controls panel) will be hidden. This improves the user experience by allowing users to focus on the flashcard content without distractions.
- Added a toggleFullscreen function to handle the fullscreen state.
- Added CSS styles to ensure the card and its container take up the full screen when expanded.
- Conditionally rendered the controls panel to hide it in fullscreen mode.
closes: #218
=> MINOR: Add fullscreen mode

CHANGELOG.md, backend/__init__.py, frontend/src/containers/DailyFlashcardBrowser/DailyFlashcardBrowser.js, frontend/src/screens/ViewFlashcards.js
Components were throwing "Cannot read properties of undefined (reading 'includes')" errors when 
attempting to access methods on undefined values, particularly when no flashcard data was available. This was causing a runtime error when navigating to the card set edit page
- Added proper existence checks before accessing properties
- Implemented array conversion for non-array values
- Added fallbacks for undefined values
- ViewFlashcards.js
- DailyFlashcardBrowser.js
Verified that the application no longer throws errors when:
- No flashcards are available
- Navigating between daily and all cards modes## Pull Requestor Checklist
Before:
After:
=> PATCH - Fix Runtime Errors in Flashcard Components

CHANGELOG.md, backend/__init__.py, frontend/src/containers/CardOverview/CardOverview.js
Turnover button is added when the user flips flashcard in "Your Daily Dose". When clicked on Turnover the flashcard unflips and question is shown #205
=> PATCH: Allow_Users_to_Unflip_Flashcards_#205

CHANGELOG.md, backend/__init__.py, backend/classes/date.py, backend/database/handlers/statistics.py, testing/test_api/test_user.py
Added
- Weekly XP reset logic
FIXES: https://github.com/jacob-macleod/Dolphin-Flashcard-App/issues/43
=> MINOR - Added weekly XP reset logic

CHANGELOG.md, backend/__init__.py, frontend/src/componments/WhiteOverlay/WhiteOverlay.css, frontend/src/componments/WhiteOverlay/WhiteOverlay.js, frontend/src/containers/CardOverview/CardOverview.js, frontend/src/containers/DailyFlashcardBrowser/DailyFlashcardBrowser.css, frontend/src/containers/TotalFlashcardBrowser/RenderTotalFlashcardBrowser.js
- Improved formatting of all cards and daily flashcard mode on fullscreen mode
- Fixed bug where "Turn over" button on flashcard did not work
=> PATCH: Mobile site update

CHANGELOG.md, backend/__init__.py, frontend/src/componments/WhiteOverlay/WhiteOverlay.css, frontend/src/containers/CardOverview/CardOverview.js, frontend/src/containers/FlashcardOverview/FlashcardOverview.js, frontend/src/containers/FlashcardRow/FlashcardRow.js, frontend/src/containers/Modal/DeleteFlashcardConfirmation/DeleteFlashcardConfirmation.js, frontend/src/screens/EditFlashcard.js, frontend/src/screens/Settings.css, frontend/src/screens/Settings.js
- Fixed bug when deleting flashcards
- Fixed formatting of FlashcardRow in Edit flashcards page
- Fixed formatting for settings page on Desktop
=> PATCH: Import flashcards bugfix

CHANGELOG.md, backend/__init__.py, backend/database/handlers/flashcards.py, frontend/src/api/config.js
Improved speed (efficiency) of card upload
=> PATCH: Improve speed of card upload

CHANGELOG.md, backend/__init__.py, frontend/src/App.css, frontend/src/App.js, frontend/src/classes/CommunitySets.js, frontend/src/componments/Logos/DolphinLogo/DolphinLogo.js, frontend/src/componments/Text/Heading2/Heading2.css, frontend/src/componments/Text/Heading2/Heading2.js, frontend/src/componments/Text/Heading2/index.js, frontend/src/componments/Text/Link/Link.css, frontend/src/componments/WhiteOverlay/WhiteOverlay.css, frontend/src/componments/WhiteOverlay/WhiteOverlay.js, frontend/src/containers/FeaturedCommunitySet/FeaturedCommunitySet.css, frontend/src/containers/FeaturedCommunitySet/FeaturedCommunitySet.js, frontend/src/containers/FeaturedCommunitySet/index.js, frontend/src/containers/FlashcardCategoryLink/FlashcardCategoryLink.js, frontend/src/containers/FlashcardCategoryLink/index.js, frontend/src/containers/FlashcardSearchResult/FlashcardSearchResult.js, frontend/src/screens/Community.css, frontend/src/screens/Community.js, frontend/src/screens/CommunityCategory.js
=> MINOR: Add design page

CHANGELOG.md, backend/__init__.py, frontend/src/containers/FlashcardOverview/FlashcardItem/FlashcardItem.js
- Fixed the bug for incorrect tagging of card status
FIXES: #34
=> MINOR - Fixed the bug for incorrect tagging of card status

CHANGELOG.md, backend/__init__.py, frontend/src/api/config.js, validate_config_files.py
=> PATCH: Update frontend config

CHANGELOG.md, README.md, backend/__init__.py, frontend/src/config.js, frontend/src/screens/AIFlashcards.js
Enabled anki and AI flashcards improvements
=> PATCH: Enabled anki import

CHANGELOG.md, backend/__init__.py, backend/database/database_abstract.py, backend/database/handlers/shared_folder_sets.py, backend/database/handlers/shared_folders.py, backend/database/shared_folder_jwt_handler.py, backend/main.py, backend/routes/api/shared_folders.py
- Shared Folders API with 16 routes, per-user progress tracking, and JWT-based invite system.
FIXES: https://github.com/jacob-macleod/Dolphin-Flashcard-App/issues/290
=> MINOR : Shared Folders API Implementation
